// currencyOptions.ts
export const CurrencyOptions = {
  USD: { label: "USD - US Dollar", symbol: "$" },
  EUR: { label: "EUR - Euro", symbol: "€" },
  UGX: { label: "UGX - Ugandan Shilling", symbol: "USh" },
  GBP: { label: "GBP - British Pound", symbol: "£" },
  JPY: { label: "JPY - Japanese Yen", symbol: "¥" },
  CAD: { label: "CAD - Canadian Dollar", symbol: "C$" },
  AUD: { label: "AUD - Australian Dollar", symbol: "A$" },
  INR: { label: "INR - Indian Rupee", symbol: "₹" },
  ZAR: { label: "ZAR - South African Rand", symbol: "R" },
  CNY: { label: "CNY - Chinese Yuan", symbol: "¥" },
  KRW: { label: "KRW - South Korean Won", symbol: "₩" },
  NGN: { label: "NGN - Nigerian Naira", symbol: "₦" },
  KES: { label: "KES - Kenyan Shilling", symbol: "KSh" },
  GHS: { label: "GHS - Ghanaian Cedi", symbol: "₵" },
  MXN: { label: "MXN - Mexican Peso", symbol: "MX$" },
  BRL: { label: "BRL - Brazilian Real", symbol: "R$" },
  RUB: { label: "RUB - Russian Ruble", symbol: "₽" },
  SEK: { label: "SEK - Swedish Krona", symbol: "kr" },
  NOK: { label: "NOK - Norwegian Krone", symbol: "kr" },
  CHF: { label: "CHF - Swiss Franc", symbol: "₣" },
  AED: { label: "AED - UAE Dirham", symbol: "د.إ" },
  SAR: { label: "SAR - Saudi Riyal", symbol: "﷼" },
};
